### ISSUE TITLE
Use helm chart in file system

### ISSUE THREAD

**Issue by dineshba** [gojekfarm/stevedore#31]
Very similar to below command, can we specify the relative or absolute path in Stevedore manifest file ?
```sh
helm install myredis ./redis
```

Note: Currently, we need to push our custom charts to `chartmuseum` and run stevedore plan/apply.

**Comment by jskswamy** [comment]
@dineshba I believe it should work, could you post the log / output of the plan/apply command with local repo?

**Comment by dineshba** [comment]
Oh sorry. It is working... Didn't know about this feature... I think we need a page where we can see list of features
